### ISSUE TITLE
REQUEST: WS public access to methods implemented at RFEM.Tools.sectionDialogue

### ISSUE THREAD

**Issue by damianbobrowski** [Dlubal-Software/RFEM_Python_Client#176]
I am looking for loading RSECTIONs.
What are the plans about releasing to public methods implemented at  `RFEM.Tools.sectionDialogue`?
Model WebService definition for RFEM version 6.02.**0030** seems to not expose used methods

```bash
> python 1.py
Connecting to server...
Traceback (most recent call last):
  File "C:\Dev\1.py", line 21, in <module>
    print(CreateSectionFromRsectionFile())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\rfem-1.12.0-py3.9.egg\RFEM\Tools\sectionDialogue.py", line 44, in CreateSectionFromRsectionFile
    model.clientModel.service.create_section_from_rsection_file(no, file_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\suds_py3-1.4.5.0-py3.9.egg\suds\client.py", line 316, in __getattr__
    return getattr(port, name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\suds_py3-1.4.5.0-py3.9.egg\suds\client.py", line 420, in __getattr__
    return getattr(m, name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\suds_py3-1.4.5.0-py3.9.egg\suds\client.py", line 511, in __getattr__
    return self[name]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\suds_py3-1.4.5.0-py3.9.egg\suds\client.py", line 524, in __getitem__
    raise MethodNotFound(qn)
suds.MethodNotFound: Method not found: 'RfemModel.RfemModelPort.create_section_from_rsection_file'
```

**Comment by OndraMichal** [comment]
Hi Damian,
the status of US-8351 is InReview, so it shouldn't take long. Reviewer told me he will try to look at it this week. So in 2 or 3 weekd it could be in GM i.e. available in WS.

**Comment by OndraMichal** [comment]
Code review put as priority.

**Comment by OndraMichal** [comment]
The US should be released in 3rd or 4th week of January 23.
